settings:
 config_version: 4.8
 prefix: '&7[&bFreeze&eGUI&7]&r '
 check_update_on_join: true

commands:
 punish_command: 'tempban %player% 7d Hack'
 slog_command: 'tempban %player% 10d Hack'

freezegui:
 display_name: '&c&lYou have been Frozen!'
 Items:
  1:
    material: PAPER
    damage: 0
    amount: 1
    name: '&c&lTeamSpeak'
    slot: 0
    lore:
    - '&eJoin in TeamSpeak'
    - ''
    - '&a&lts.example.com'
    - ''
    - '&7Click to allert the Staff'
    - '&7that you are entering our TeamSpeak'
    - ''
    - '&c&lSLOG=BAN'
  2:
   material: CHEST
   damage: 0
   amount: 1
   name: '&c&lADMITTED CHEAT'
   slot: 4
   lore:
   - '&cIf you click here, your ban'
   - '&7will be reduced'
  3:
   material: PAPER
   damage: 0
   amount: 1
   name: '&c&lJOIN TS'
   name: '&c&lTeamSpeak'
   slot: 8
   lore:
   - '&eJoin in TeamSpeak'
   - ''
   - '&a&lts.example.com'
   - ''
   - '&7Click to allert the Staff'
   - '&7that you are entering our TeamSpeak'
   - ''
   - '&c&lSLOG=BAN'

suregui:
 display_name: '&c&lConfirm?'
 Items:
  1:
   material: WOOL
   damage: 13
   amount: 1
   name: '&c&lYes'
   slot: 2
   lore:
   - '&cConfirm that you are using Hack'
  2:
   material: WOOL
   damage: 14
   amount: 1
   name: '&c&lNo'
   slot: 6
   lore:
   - '&cGo back'

freezeallgui:
 display_name: '&c&lFreeze ALL!'
 Items:
  1:
   material: BOOK
   damage: 0
   amount: 1
   name: '&c&lFreeze ALL'
   slot: 4
   lore:
   - '&cThe server is in &eFreezeAll-Mode'